Lang = {
	-- Notifications:
	['no_players_nearby'] = 'No players nearby.',
	['no_vehicle_nearby'] = 'No vehicle nearby.',
	['must_be_inside_veh'] = 'You must be inside a vehicle.',
	['only_admins_can_do_this'] = 'Only admins can perform this action.',
	['no_tuner_shops'] = 'There are no tuner shops registered.',
	['you_are_not_boss'] = 'You are not boss - no access!',
	['not_hired_in_any_shops'] = 'You are not hired in any tuner shops!',
	['you_assigned_new_boss'] = 'You assigned a new boss (%s) to the shop: %s.',
	['you_clocked_off_duty'] = 'You clocked off-duty.',
	['you_clocked_on_duty'] = 'You clocked on-duty.',
	['input_required'] = 'You must provide an input.',
	['input_amount_higher_0'] = 'Entered amount must be higher than 0.',
	['account_withdraw_max'] = 'You cannot withdraw more than what\'s in the account.',
	['money_deposited'] = 'You deposited $%s into the shop account.',
	['money_withdrawn'] = 'You withdrew $%s from the shop account.',
	['account_money_plus'] = 'Account increased with +$%s',
	['account_money_minus'] = 'Account decreased with -$%s',
	['not_enough_money'] = 'Not enough money.',
	['insufficient_funds'] = 'Insufficient funds in shop account.',
	['no_owned_vehicles'] = 'You have no owned vehicles.',
	['your_inventory_empty'] = 'Your inventory is empty.',
	['you_dont_have_x_item'] = 'You do not have %s in your inventory.',
	['you_need_x_amount_item'] = 'You only have %sx %s - required amount is %sx',
	['you_crafted_x_item'] = 'You crafted %sx %s.',
	['parts_sent_to_storage'] = 'Your ordered parts have been delivered to the storage.',
	['no_categories_to_show'] = 'No mod categories to display.',
	['vehicle_no_mod_category'] = 'The vehicle has no available mods in this category: %s.',
	['no_variants_for_mod'] = 'No mod variants available for this mod: %s.',
	['mod_variant_already_installed'] = 'Selected mod variant is already installed.',
	['move_closer_mod_interaction'] = 'Move closer to the %s.',
	['must_be_standing_hood'] = 'You must be standing in front of the hood.',
	['must_be_standing_wheel'] = 'You must be standing close to a wheel.',
	['no_veh_in_direction'] = 'There is no vehicle in that direction.',
	['veh_must_be_repaired_to_mod'] = 'Vehicle must be repaired to begin installing mods.',
	['paid_repair_cost'] = 'You paid %s to repair the vehicle.',
	['no_bills_to_show'] = 'No bills have been invoiced yet to show.',
	['you_declined_bill'] = 'You declined a bill of $%s from: %s.',
	['you_paid_a_bill'] = 'You paid a bill of $%s from: %s.',
	['bill_sent_to_x'] = 'You sent a bill of $%s to %s.',
	['bill_x_no_money'] = '%s cannot cover the cost of the bill.',
	['bill_paid_by_x'] = '%s has paid your bill of $%s.',
	['bill_declined_by_x'] = '%s has declined to pay your bill of $%s.',
	['employee_recruit_sent'] = 'You sent recruitment papers to: %s.',
	['employee_already_hired'] = 'The player is already recruitted in your shop.',
	['recruitment_accepted'] = 'You accepted the shop recruitment.',
	['recruitment_declined'] = 'You declined the shop recruitment.',
	['recruitment_accepted2'] = 'Player has accepted the recruitment and is now hired in the shop.',
	['recruitment_declined2'] = 'Player has declined the recruitment.',
	['cannot_fire_boss'] = 'You cannot fire the boss, idiot.',
	['fired_employee'] = 'You fired %s from the shop.',
	['cannot_demote_boss'] = 'You cannot demote/promote the boss, idiot.',
	['employee_grade_updated'] = 'You updated %s\'s job-grade.',

	-- Context | Title:
	['title_yes'] = 'Yes',
	['title_no'] = 'No',
	['title_tuning_admin'] = 'Tuning System [Admin]',
	['title_tuning_player'] = 'Player Tuning Menu',
	['title_view_shops'] = 'View Tuner Shops',
	['title_admin_manage_shop'] = 'Manage Shop: %s [%s]',
	['title_admin_set_boss'] = 'Set Boss',
	['title_toggle_duty_menu'] = 'Toggle Duty',
	['title_on_duty_state'] = 'On Duty: %s',
	['title_clock_in_out'] = 'Clock In/Out',
	['title_boss_menu'] = 'Boss Menu',
	['title_tuner_account'] = 'Account',
	['title_tuner_employees'] = 'Employees',
	['title_account_balance'] = 'Account Balance',
	['title_account_deposit'] = 'Deposit',
	['title_account_withdraw'] = 'Withdraw',
	['title_manage_employees'] = 'Manage Employees',
	['title_recruit_employees'] = 'Recruit Employees',
	['title_accept_recruitment'] = 'Accept Recruitment From %s',
	['title_fire_employee'] = 'Fire Employee',
	['title_promote_emplotee'] = 'Promote Employee',
	['title_tuner_garage'] = 'Garage',
	['title_garage_get_veh'] = 'Get Vehicle',
	['title_garage_store_veh'] = 'Store Vehicle',
	['title_garage_vehicles'] = 'Vehicles',
	['title_storage'] = 'Storage',
	['title_withdraw_storage'] = 'Withdraw Items',
	['title_deposit_storage'] = 'Deposit Items',
	['desc_withdraw_storage'] = 'View or withdraw items from storage.',
	['desc_deposit_storage'] = 'Deposit items from your inventory into storage.',
	['title_workbench'] = 'Workbench',
	['title_laptop'] = 'Laptop',
	['title_billing'] = 'Billing',
	['title_npc_jobs'] = 'NPC jobs',
	['title_repair_vehicle'] = 'Repair Vehicle',
	['title_cancel_job'] = 'Cancel Current Job',
	['title_select_job_type'] = 'Select Job Type',
	['title_create_bill'] = 'Create Bill',
	['title_view_bills'] = 'View Bills',
	['title_generate_bill'] = 'Generate Bill',
	['title_select_bill_plate'] = 'Select Plate To Bill',
	['title_bill_plate_x'] = '%s | Total: %s',
	['title_bill_overview'] = '%s | $%s',
	['title_bill_respond'] = 'Pay Bill: $%s',
	['title_bill_send_bill'] = 'Send Bill - %s',
	['title_bill_payment'] = 'Pay Bill - %s',
	['title_bill_plate_overview'] = 'Bill Overview - %s',
	['title_bill_send'] = 'Send Bill',
	['title_bill_item_price_display'] = '%s - %s',
	['title_cur_veh_upgrades'] = 'Vehicle Performance Mods',
	['title_install_vehicle_upg'] = 'Install Vehicle Upgrades',
	['title_upg_install_turbo'] = 'Install Turbo Upgrade',
	['title_upg_uninstall_turbo'] = 'Uninstall Turbo Upgrade',
	['title_upg_show_upgrades'] = '%s - %s - Installed',
	['title_install'] = 'Install',

	-- Context | Meta Data:
	['meta_shop_id'] = 'ID',
	['meta_boss'] = 'Boss Name',
	['meta_boss_id'] = 'Boss Id:',
	['meta_job_name'] = 'Job Name',
	['meta_player_id'] = 'Player ID',
	['meta_job_grade'] = 'Grade',
	['meta_identifier'] = 'Identifier',
	['meta_not_answered'] = 'N/A',
	['meta_job_label_and_name'] = '%s [%s]',
	['meta_veh_make'] = 'Make',
	['meta_veh_model'] = 'Model',
	['meta_veh_plate'] = 'Plate',
	['meta_option_engine'] = 'Engine',
	['meta_option_body'] = 'Body',
	['meta_option_fuel'] = 'Fuel',
	['meta_bill_ref'] = 'Reference',
	['meta_bill_shop'] = 'Shop',
	['meta_bill_sender'] = 'Sender',
	['meta_bill_receiver'] = 'Receiver',
	['meta_bill_amount'] = 'Bill Amount',
	['meta_bill_date'] = 'Date',
	['meta_bill_time'] = 'Time',
	['meta_mod_name'] = 'Mod Name',
	['meta_mod_label'] = 'Mod Label',
	['meta_mod_variant_label'] = 'Variant Label',
	['meta_mod_total'] = 'Total Price',
	['meta_mod_labor_fee'] = 'Labor Fee',
	['meta_mod_part_acquisition'] = 'Part Acquisition',
	['meta_upg_installed'] = 'Installed',
	['meta_upg_installed_yes'] = 'Yes',
	['meta_upg_installed_no'] = 'No',
	['meta_installed_upgrade'] = 'Installed Upgrade',
	['meta_max_available_upgs'] = 'Max Available Upgrades',

	-- Context | Description:
	['desc_admin_set_boss'] = 'Set a boss for the shop',
	['desc_admin_click_to_set_boss'] = 'Click to set as boss for the shop.',
	['desc_manage_employees'] = 'View and manage employees.',
	['desc_recruit_employee'] = 'Click to recruit employee.',
	['desc_fire'] = 'Click to fire employee from the shop',
	['desc_promote'] = 'Click to promote employee job grade',
	['desc_pay_bill'] = 'Click to pay the bill',
	['desc_send_bill'] = 'Click to send the bill',

	-- Context | Input:
	['input_title_withdraw'] = 'Withdraw: %s [%sx]',
	['input_title_deposit'] = 'Deposit: %s [%sx]',
	['input_title_order_parts'] = '%s - %s / part',
	['input_title_confirm_order_parts'] = 'Confirm: %sx %s for: %s',
	['input_title_rgb_color'] = 'RGB Color Picker',

	['input_account_cur_balance'] = 'Current Balance',
	['input_account_deposit_amount'] = 'Deposit Amount',
	['input_account_withdraw_amount'] = 'Withdraw Amount',
	['input_storage_deposit_amount'] = 'Deposit Amount',
	['input_storage_withdraw_amount'] = 'Withdraw Amount',
	
	['input_label_bill_player'] = 'Player',
	['input_label_bill_amount'] = 'Bill Amount',
	['input_label_bill_note'] = 'Note',
	['input_label_bill_date'] = 'Date',
	['input_label_bill_time'] = 'Time',

	['input_label_order_quantity'] = 'Quantity',
	['input_label_order_confirm'] = 'Confirm',
	['input_label_rgb_color'] = 'Colour Input',
	['input_desc_order_quantity'] = 'Enter amount of %s parts to order.',

	['input_desc_bill_player'] = 'Select a player to bill',
	['input_desc_bill_note'] = 'Enter notes for the bill',

	-- Options | Label:
	['options_label_cur_tyre_smoke'] = 'Current Tyre Smoke [%s, %s, %s]',
	['options_label_tyre_smoke_preview_pick_color'] = 'Preview [Pick Color]',
	['options_label_tyre_smoke_preview_x'] = 'Preview [%s, %s, %s]',
	['options_label_rgb_color'] = 'RGB Color',

	['options_value_pick_color_first'] = 'First Pick a Color',
	['options_value_pick_color_tool'] = 'Color Picker Tool',

	['options_desc_tyre_smoke_preview'] = 'Click to preview tyre smoke color',
	['options_desc_rgb_color'] = 'Pick color and then scroll to next button to install',

	-- Alerts | Content:
	['repair_alert_modshop'] = 'Price: %s \n\n Engine Health: %s \n\n Body Health: %s'
}