Config.StoreOutfitOption = true
Config.Stores = {
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-525.58, -611.31, 40.43),
        length = 2, width = 2,
        blip = {enable = false, color = 47, sprite = 366, size = 0.7},
        price = 0,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-566.79, -586.16, 33.68),
        length = 2, width = 2,
        blip = {enable = false, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(1693.32, 4823.48, 41.06),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-712.21, -155.35, 36.41),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-1192.94, -772.68, 16.32),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(425.236, -806.008, 28.491),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-162.658, -303.397, 38.733),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(75.950, -1392.891, 28.376),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-822.194, -1074.134, 10.328),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-1450.711, -236.83, 48.809),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(4.254, 6512.813, 30.877),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(615.180, 2762.933, 41.088),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(1196.785, 2709.558, 37.222),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-3171.453, 1043.857, 19.863),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-1100.959, 2710.211, 18.107),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(-1207.65, -1456.88, 3.37),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = 'Clothing Shop',
        container = {
            {type = 'clothing', title ='Clothing'}, 
            {type = 'accessoires', title ='accessoires'},
        },
        coords = vector3(121.76, -224.6, 53.56),
        length = 2, width = 2,
        blip = {enable = true, color = 47, sprite = 366, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'},
        },
        coords = vector3(-814.3, -183.8, 36.6),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(136.8, -1708.4, 28.3),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(-1282.6, -1116.8, 6.0),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(1931.5, 3729.7, 31.8),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(1212.8, -472.9, 65.2),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(-32.9, -152.3, 56.1),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(-278.1, 6228.5, 30.7),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Barber Shop",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(-553.02, -583.92, 40.43),
        length = 2, width = 2,
        blip = {enable = false, color = 0, sprite = 71, size = 0.7},
        price = 250,
    },
    {   name = "Nails & Beauty",
        container = {
            {type = 'barber', title ='Barber'}, 
        },
        coords = vector3(65.68, -1446.44, 28.32),
        length = 2, width = 2,
        blip = {enable = true, color = 0, sprite = 71, size = 1.0},
        price = 250,
    },

    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(1322.6, -1651.9, 51.2),
        length = 2, width = 2,
        blip = {enable = true, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(-1153.6, -1425.6, 4.9),
        length = 2, width = 2,
        blip = {enable = true, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(-3170.0, 1075.0, 20.8),
        length = 2, width = 2,
        blip = {enable = true, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(1864.6, 3747.7, 33.0),
        length = 2, width = 2,
        blip = {enable = true, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(-293.7, 6200.0, 31.4),
        length = 2, width = 2,
        blip = {enable = true, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    {   name = "Tattoos",
        container = {
            {type = 'tattoos', title ='Tattoos'}, 
        },
        coords = vector3(-586.27, -599.71, 41.43),
        length = 2, width = 2,
        blip = {enable = false, color = 1, sprite = 75, size = 0.8},
        price = 250,
    },
    
}
