DROP TABLE IF EXISTS `ak47_qb_sitchair`;
CREATE TABLE IF NOT EXISTS `ak47_qb_sitchair` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pos` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb3;